ln -rsf ./nvim/ ~/.config/
ln -rsf ./config/.bashrc ~/
ln -rsf ./config/.tmux.conf ~/
ln -rsf ./config/.gitconfig ~/
ln -rsf ./config/.ignore ~/workspace/
ln -rsf ./config/alacritty.yml ~/.config/alacritty/
ln -rsf ./config/foot.ini ~/.config/foot/
ln -rsf ./config/firefox/chrome/ ~/.mozilla/firefox/e4xc206r.default-release/
ln -rsf ./config/config.fish ~/.config/fish/
ln -rsf ./config/sway/config ~/.config/sway/
